services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/ 
      - ./mongo_data:/data/db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend